### ISSUE TITLE
Nested folders not considered in markdown images

### ISSUE THREAD

**Issue by luisalima** [Bhacaz/docs-as-code-confluence#12]
I have a markdown file that has an image reference like so:

```md
![](./image.svg)
```

the file and the image are in a nested subfolder `projects/sub1/sub2/file.md`, `projects/sub1/sub2/image.svg`

Getting

```sh
Error: ENOENT: no such file or directory, open './projects/./image.svg'
Emitted 'error' event on Request instance at:
}
```

The action is configured as:

```yaml
      - name: Sync projects folder to confluence
        uses: Bhacaz/docs-as-code-confluence@v2
        with:
          folder: projects
          username: ${{ secrets.CONFLUENCE_USERNAME }}
          password: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-base-url: ${{ secrets.CONFLUENCE_BASE_URL }}
          space-key: ${{ secrets.CONFLUENCE_SPACE_KEY }}
          parent-page-id: 131891301
```

Thanks in advance!
